### ISSUE TITLE
--list-config license enhancement

### ISSUE THREAD

**Issue by jmcc0nn3ll** [jetty/jetty.project#265]
migrated from Bugzilla [#483677](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483677)
status NEW severity _enhancement_ in component _start_ for _9.3.x_
Reported in version _9.3.6_ on platform _PC_
Assigned to: Joakim Erdfelt

On 2015-12-04 09:22:49 -0500, Jesse McConnell wrote:

> would be a nice feature to be able to indicate the license for each jar listed in the --list-config command

**Comment by joakime** [comment]
@gregw this sounds like a good task for lachlan, wdyt?

**Comment by gregw** [comment]
@joakime I think the start code is probably a bit confusing as it's had so many maintainers... but we will see

**Comment by strogiyotec** [comment]
@joakime  @gregw  @sbordet  I made a PR
https://github.com/eclipse/jetty.project/pull/9964
Could you take a look please

**Comment by sbordet** [comment]
@strogiyotec thanks for the PR.
Looking at your implementation, you could use `JarFile.getManifest()`.

However, I think it's opening a can of worms, as looking up `Bundle-License` from the manifest works only for OSGi...
@strogiyotec has designed for other means to lookup the license, but what if there are multiple licenses? 
We risk presenting EPL 2, when can also be AL 2, etc.

I feel we won't be able to be precise, and at that point better to not present anything.

@joakime what do you think?

**Comment by gregw** [comment]
> I feel we won't be able to be precise, and at that point better to not present anything.

We actually have an obligation to present our licenses correctly, as our attempt at doing so is the `NOTICE.txt` file.    It would be nice if we could generate the contents of that through something like this, rather than have it be manually maintained. 

For our own jars, there is no excuse for the manifest not to be accurate with regards to licenses.  For our dependencies, we can raise issues to get them to correct any issues.

Ultimately you care about the the things you measure.   If we don't report on the license listings in the manifest, then they will still be in-precise/wrong... we just wont notice it.   Is that any better?

**Comment by sbordet** [comment]
@gregw from the PR output I was surprised that `slf4j-api.jar` 2.0.5 does not have a license and indeed does not have neither `Bundle-License` nor a LICENSE.txt file.

Turns out in 2.0.7 there is `META-INF/LICENSE.txt`, but it is the MIT one, which would be incredibly difficult to recognize and parse. Fortunately it also has `Bundle-License`.

Perhaps we can just rely on `Bundle-License` and say `unknown` otherwise. 
The idea being that we do the minimum work to figure it out, not the maximal effort.
